### ISSUE TITLE
Adding two more papers

### ISSUE THREAD

**Issue by daisukelab** [Lupin1998/Awesome-MIM#1]
Hello, thanks for a nice summary. I think we could add two more papers (at least, maybe more papers are coming...).

- https://arxiv.org/abs/2208.00449 - Clearly a following work of MAE.
- https://arxiv.org/abs/2202.03555 - This can also be a MIM.

Thanks!

**Comment by Lupin1998** [comment]
Hi, @daisukelab, thanks for your advice. I have added the two papers ([SdAE](https://arxiv.org/abs/2208.00449) and [data2vec](https://arxiv.org/abs/2202.03555)) you mentioned in the [latest commit](https://github.com/Lupin1998/Awesome-MIM/commit/dba5ce2de930138d6725ac6e5e5f3c00b210dd6f). Thanks again for your attention and efforts.
