### ISSUE TITLE
MST is the first work in MIM with Advanced Masking (attention-guided mask strategy) in NIPS 2021, it is not only the MIM + contrastive learning.

### ISSUE THREAD

**Issue by CASlzwde** [Lupin1998/Awesome-MIM#5]

**Comment by Lupin1998** [comment]
Thanks for your suggestion @CASlzwde. We have fixed this issue in the latest commit. We are working on the MIM survey and will classify MST into two categories, i.e., advanced masking and combining MIM and CL.
