### ISSUE TITLE
Request to add a paper

### ISSUE THREAD

**Issue by yangjiangeyjg** [Lupin1998/Awesome-MIM#6]
Hi, thanks for your great survey. 

May I ask if it is possible to add a paper of AAAI 2023: [CoMAE](https://ojs.aaai.org/index.php/AAAI/article/view/25419/25191) - About of MIM and CL for RGB-D understanding.

**Comment by Lupin1998** [comment]
Hi, @yangjiangeyjg. Thanks for your attention and suggestion of masked modeling work for 2D depth estimation. We have added this paper to our awesome list and the [latest version](https://github.com/Lupin1998/Awesome-MIM/blob/master/files/Survey_on_Masked_Modeling_Latest_Version.pdf) of the survey. Feel free to open new issue if there are more relevant papers for masked modeling topics.

**Comment by yangjiangeyjg** [comment]
> Hi, @yangjiangeyjg. Thanks for your attention and suggestion of masked modeling work for 2D depth estimation. We have added this paper to our awesome list and the [latest version](https://github.com/Lupin1998/Awesome-MIM/blob/master/files/Survey_on_Masked_Modeling_Latest_Version.pdf) of the survey. Feel free to open new issue if there are more relevant papers for masked modeling topics.

Hi, @Lupin1998. CoMAE presents a curriculum learning strategy to unify contrastive learning and masked image modeling for RGB-D understanding orther than 2D depth estimation. I would like to apply for a modification to it. Thanks! #7
