### ISSUE TITLE
Errors in the author information of a paper in README

### ISSUE THREAD

**Issue by JeremyZhao1998** [Lupin1998/Awesome-MIM#8]
### Errors in the author information of paper: Masked Retraining Teacher-student Framework for Domain Adaptive Object Detection

Hi, thanks for your excellent work. I am the author of the paper:
**Masked Retraining Teacher-student Framework for Domain Adaptive Object Detection**
Thanks for citing our work. 

I found that the author information of the paper is incorrect in the README file:

**Masked Retraining Teacher-student Framework for Domain Adaptive Object Detection**
_Yuan Liu, Songyang Zhang, Jiacheng Chen, Zhaohui Yu, Kai Chen, Dahua Lin_

The correct author information should be:

_Zijing Zhao, Sitong Wei, Qingchao Chen, Dehui Li, Yifan Yang, Yuxin Peng, Yang Liu_

Hope you can correct it. Thanks again for your great work!

**Comment by Lupin1998** [comment]
Hi, @JeremyZhao1998. Thanks for your attention and for reporting typos in your repo! We have fixed this error in the latest commit. Feel free to open a new issue or pull a request if you find other typos or want to add a new paper for the masked modeling topic. I will close this issue if there are no more problems.
