### ISSUE TITLE
About Arxiv paper updates

### ISSUE THREAD

**Issue by yangjiangeyjg** [Lupin1998/Awesome-MIM#9]
Hello, I would like to know if you have any plans to update your arxiv paper in the near future. Thanks!

**Comment by Lupin1998** [comment]
Hi, @yangjiangeyjg. Thanks for your contribution to Awesome-MIM! We plan to update the arXiv version every four months till the manuscript is published. We could revise before May to add more recently proposed AIGC methods (e.g., video generation) that use Masked Image Modeling techniques. If you are interested in our survey, we can talk about it in more detail (you can reach me by WeChat, Lupin_1998).

**Comment by yangjiangeyjg** [comment]
Thanks very much!
